apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: application
  name: application
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: application
status:
  loadBalancer: {}
