kind: ConfigMap
apiVersion: v1
metadata:
  name: easyappointment-config
  namespace: default
data:
  DB_USERNAME: easyapp
  DB_NAME: easyapp
  DB_PASSWORD: veryhardpassword
  DB_HOST: database:3306
  MYSQL_DATABASE: easyapp
  MYSQL_PASSWORD: veryhardpassword
  MYSQL_ROOT_PASSWORD: veryhardpassword
  MYSQL_USER: easyapp
  APP_URL: localhost
  APP_HOST: 0.0.0.0
  APP_PORT: "80"
  EMAIL_PROTOCOL: mail
  SMTP_HOST: smtp.gmail.com
  SMTP_USER: user
  SMTP_PASS: password
  SMTP_CRYPTO: ssl
  SMTP_PORT: "25"
