apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: database
  name: database
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: database
status:
  loadBalancer: {}
